[package]
name = "ros"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader_api = { path = "../bootloader_api" }
serial = { path = "../serial" }
uefi = { path = "../uefi" }
